default:
  item: "130:0"
  name: "§r§e战利品袋"
  lore:
    - "§r§7\n容量: §e%size%  §7当前:§e %count%"
    - "§r§7\n右键/点击地面 §e开启"
  #支持 big(54) small (27) soSmall (5)
  size: soSmall
  remove: true
  sneaking-rename: false
small:
  item: "130:0"
  name: "§r§e手提袋"
  lore:
    - "§r§7\n容量: §e%size%  §7当前:§e %count%"
    - "§r§7\n右键/点击地面 §e开启"
  #支持 big(54) small (27) soSmall (5)
  size: small
  remove: false
  sneaking-rename: false
